# Generated by Django 4.1.13 on 2025-07-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, choices=[('Istanbul', 'Istanbul'), ('Ankara', 'Ankara'), ('Izmir', 'Izmir')], max_length=100, null=True),
        ),
    ]
