# Generated by Django 4.1.13 on 2025-07-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
