# Generated by Django 4.2.26 on 2025-11-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ilce',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mahalle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
