# Generated by Django 4.2.26 on 2025-11-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_user_managers_alter_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='finansal_kod_numarasi',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Finansal Kod Numarası'),
        ),
    ]
