# Generated by Django 4.2.26 on 2025-11-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_user_finansal_kod_numarasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='finansal_kod_numarasi',
            field=models.CharField(blank=True, default='1', max_length=10, null=True, verbose_name='Finansal Kod Numarası'),
        ),
    ]
