# Generated by Django 4.2.26 on 2025-11-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_rename_ilgi_alanlari'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hobilerim',
            field=models.TextField(blank=True, null=True, verbose_name='Hobilerim'),
        ),
        migrations.AddField(
            model_name='user',
            name='ilgi_alanlarim',
            field=models.TextField(blank=True, null=True, verbose_name='İlgi Alanlarım'),
        ),
        migrations.AddField(
            model_name='user',
            name='meslegim',
            field=models.TextField(blank=True, null=True, verbose_name='Mesleğim'),
        ),
        migrations.AddField(
            model_name='user',
            name='yeteneklerim',
            field=models.TextField(blank=True, null=True, verbose_name='Yeteneklerim'),
        ),
    ]
